version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: prod.Dockerfile
    volumes:
      - ./:/app
    ports:
      - '7190:8080'
    networks:
      - will-test
    tty: true

networks:
  will-test:
    driver: bridge